/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReferenceIndexRouteImport } from './routes/reference.index'
import { Route as HowToIndexRouteImport } from './routes/how-to.index'
import { Route as ReferenceSystemsOfCareRouteImport } from './routes/reference.systems-of-care'
import { Route as ReferenceScopeRouteImport } from './routes/reference.scope'
import { Route as ReferenceLinksRouteImport } from './routes/reference.links'
import { Route as ReferenceContactsRouteImport } from './routes/reference.contacts'
import { Route as HowToScreeningRouteImport } from './routes/how-to.screening'
import { Route as HowToFlagsLogRouteImport } from './routes/how-to.flags-log'
import { Route as HowToEventsRouteImport } from './routes/how-to.events'
import { Route as DecideReportingRouteImport } from './routes/decide.reporting'
import { Route as DecideCriticalIncidentRouteImport } from './routes/decide.critical-incident'
import { Route as DecideConflictRouteImport } from './routes/decide.conflict'
import { Route as DecideConfidentialityRouteImport } from './routes/decide.confidentiality'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceIndexRoute = ReferenceIndexRouteImport.update({
  id: '/reference/',
  path: '/reference/',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToIndexRoute = HowToIndexRouteImport.update({
  id: '/how-to/',
  path: '/how-to/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceSystemsOfCareRoute = ReferenceSystemsOfCareRouteImport.update({
  id: '/reference/systems-of-care',
  path: '/reference/systems-of-care',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceScopeRoute = ReferenceScopeRouteImport.update({
  id: '/reference/scope',
  path: '/reference/scope',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceLinksRoute = ReferenceLinksRouteImport.update({
  id: '/reference/links',
  path: '/reference/links',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceContactsRoute = ReferenceContactsRouteImport.update({
  id: '/reference/contacts',
  path: '/reference/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToScreeningRoute = HowToScreeningRouteImport.update({
  id: '/how-to/screening',
  path: '/how-to/screening',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToFlagsLogRoute = HowToFlagsLogRouteImport.update({
  id: '/how-to/flags-log',
  path: '/how-to/flags-log',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToEventsRoute = HowToEventsRouteImport.update({
  id: '/how-to/events',
  path: '/how-to/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DecideReportingRoute = DecideReportingRouteImport.update({
  id: '/decide/reporting',
  path: '/decide/reporting',
  getParentRoute: () => rootRouteImport,
} as any)
const DecideCriticalIncidentRoute = DecideCriticalIncidentRouteImport.update({
  id: '/decide/critical-incident',
  path: '/decide/critical-incident',
  getParentRoute: () => rootRouteImport,
} as any)
const DecideConflictRoute = DecideConflictRouteImport.update({
  id: '/decide/conflict',
  path: '/decide/conflict',
  getParentRoute: () => rootRouteImport,
} as any)
const DecideConfidentialityRoute = DecideConfidentialityRouteImport.update({
  id: '/decide/confidentiality',
  path: '/decide/confidentiality',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/decide/confidentiality': typeof DecideConfidentialityRoute
  '/decide/conflict': typeof DecideConflictRoute
  '/decide/critical-incident': typeof DecideCriticalIncidentRoute
  '/decide/reporting': typeof DecideReportingRoute
  '/how-to/events': typeof HowToEventsRoute
  '/how-to/flags-log': typeof HowToFlagsLogRoute
  '/how-to/screening': typeof HowToScreeningRoute
  '/reference/contacts': typeof ReferenceContactsRoute
  '/reference/links': typeof ReferenceLinksRoute
  '/reference/scope': typeof ReferenceScopeRoute
  '/reference/systems-of-care': typeof ReferenceSystemsOfCareRoute
  '/how-to/': typeof HowToIndexRoute
  '/reference/': typeof ReferenceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/decide/confidentiality': typeof DecideConfidentialityRoute
  '/decide/conflict': typeof DecideConflictRoute
  '/decide/critical-incident': typeof DecideCriticalIncidentRoute
  '/decide/reporting': typeof DecideReportingRoute
  '/how-to/events': typeof HowToEventsRoute
  '/how-to/flags-log': typeof HowToFlagsLogRoute
  '/how-to/screening': typeof HowToScreeningRoute
  '/reference/contacts': typeof ReferenceContactsRoute
  '/reference/links': typeof ReferenceLinksRoute
  '/reference/scope': typeof ReferenceScopeRoute
  '/reference/systems-of-care': typeof ReferenceSystemsOfCareRoute
  '/how-to': typeof HowToIndexRoute
  '/reference': typeof ReferenceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/decide/confidentiality': typeof DecideConfidentialityRoute
  '/decide/conflict': typeof DecideConflictRoute
  '/decide/critical-incident': typeof DecideCriticalIncidentRoute
  '/decide/reporting': typeof DecideReportingRoute
  '/how-to/events': typeof HowToEventsRoute
  '/how-to/flags-log': typeof HowToFlagsLogRoute
  '/how-to/screening': typeof HowToScreeningRoute
  '/reference/contacts': typeof ReferenceContactsRoute
  '/reference/links': typeof ReferenceLinksRoute
  '/reference/scope': typeof ReferenceScopeRoute
  '/reference/systems-of-care': typeof ReferenceSystemsOfCareRoute
  '/how-to/': typeof HowToIndexRoute
  '/reference/': typeof ReferenceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/decide/confidentiality'
    | '/decide/conflict'
    | '/decide/critical-incident'
    | '/decide/reporting'
    | '/how-to/events'
    | '/how-to/flags-log'
    | '/how-to/screening'
    | '/reference/contacts'
    | '/reference/links'
    | '/reference/scope'
    | '/reference/systems-of-care'
    | '/how-to/'
    | '/reference/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/decide/confidentiality'
    | '/decide/conflict'
    | '/decide/critical-incident'
    | '/decide/reporting'
    | '/how-to/events'
    | '/how-to/flags-log'
    | '/how-to/screening'
    | '/reference/contacts'
    | '/reference/links'
    | '/reference/scope'
    | '/reference/systems-of-care'
    | '/how-to'
    | '/reference'
  id:
    | '__root__'
    | '/'
    | '/decide/confidentiality'
    | '/decide/conflict'
    | '/decide/critical-incident'
    | '/decide/reporting'
    | '/how-to/events'
    | '/how-to/flags-log'
    | '/how-to/screening'
    | '/reference/contacts'
    | '/reference/links'
    | '/reference/scope'
    | '/reference/systems-of-care'
    | '/how-to/'
    | '/reference/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DecideConfidentialityRoute: typeof DecideConfidentialityRoute
  DecideConflictRoute: typeof DecideConflictRoute
  DecideCriticalIncidentRoute: typeof DecideCriticalIncidentRoute
  DecideReportingRoute: typeof DecideReportingRoute
  HowToEventsRoute: typeof HowToEventsRoute
  HowToFlagsLogRoute: typeof HowToFlagsLogRoute
  HowToScreeningRoute: typeof HowToScreeningRoute
  ReferenceContactsRoute: typeof ReferenceContactsRoute
  ReferenceLinksRoute: typeof ReferenceLinksRoute
  ReferenceScopeRoute: typeof ReferenceScopeRoute
  ReferenceSystemsOfCareRoute: typeof ReferenceSystemsOfCareRoute
  HowToIndexRoute: typeof HowToIndexRoute
  ReferenceIndexRoute: typeof ReferenceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/': {
      id: '/reference/'
      path: '/reference'
      fullPath: '/reference/'
      preLoaderRoute: typeof ReferenceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to/': {
      id: '/how-to/'
      path: '/how-to'
      fullPath: '/how-to/'
      preLoaderRoute: typeof HowToIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/systems-of-care': {
      id: '/reference/systems-of-care'
      path: '/reference/systems-of-care'
      fullPath: '/reference/systems-of-care'
      preLoaderRoute: typeof ReferenceSystemsOfCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/scope': {
      id: '/reference/scope'
      path: '/reference/scope'
      fullPath: '/reference/scope'
      preLoaderRoute: typeof ReferenceScopeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/links': {
      id: '/reference/links'
      path: '/reference/links'
      fullPath: '/reference/links'
      preLoaderRoute: typeof ReferenceLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/contacts': {
      id: '/reference/contacts'
      path: '/reference/contacts'
      fullPath: '/reference/contacts'
      preLoaderRoute: typeof ReferenceContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to/screening': {
      id: '/how-to/screening'
      path: '/how-to/screening'
      fullPath: '/how-to/screening'
      preLoaderRoute: typeof HowToScreeningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to/flags-log': {
      id: '/how-to/flags-log'
      path: '/how-to/flags-log'
      fullPath: '/how-to/flags-log'
      preLoaderRoute: typeof HowToFlagsLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to/events': {
      id: '/how-to/events'
      path: '/how-to/events'
      fullPath: '/how-to/events'
      preLoaderRoute: typeof HowToEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decide/reporting': {
      id: '/decide/reporting'
      path: '/decide/reporting'
      fullPath: '/decide/reporting'
      preLoaderRoute: typeof DecideReportingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decide/critical-incident': {
      id: '/decide/critical-incident'
      path: '/decide/critical-incident'
      fullPath: '/decide/critical-incident'
      preLoaderRoute: typeof DecideCriticalIncidentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decide/conflict': {
      id: '/decide/conflict'
      path: '/decide/conflict'
      fullPath: '/decide/conflict'
      preLoaderRoute: typeof DecideConflictRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decide/confidentiality': {
      id: '/decide/confidentiality'
      path: '/decide/confidentiality'
      fullPath: '/decide/confidentiality'
      preLoaderRoute: typeof DecideConfidentialityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DecideConfidentialityRoute: DecideConfidentialityRoute,
  DecideConflictRoute: DecideConflictRoute,
  DecideCriticalIncidentRoute: DecideCriticalIncidentRoute,
  DecideReportingRoute: DecideReportingRoute,
  HowToEventsRoute: HowToEventsRoute,
  HowToFlagsLogRoute: HowToFlagsLogRoute,
  HowToScreeningRoute: HowToScreeningRoute,
  ReferenceContactsRoute: ReferenceContactsRoute,
  ReferenceLinksRoute: ReferenceLinksRoute,
  ReferenceScopeRoute: ReferenceScopeRoute,
  ReferenceSystemsOfCareRoute: ReferenceSystemsOfCareRoute,
  HowToIndexRoute: HowToIndexRoute,
  ReferenceIndexRoute: ReferenceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
